server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka     
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  flyway:
    url: jdbc:mysql://localhost:3306/cambio?useTimezone=true&serverTimezone=UTC
    user: root
    password: 123456
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs        